### ISSUE TITLE
Elaboração do Rich Picture

### ISSUE THREAD

**Issue by klyssmannoliveira** [Requisitos-de-Software/2021.2-PontoFacil#2]
# Descrição:
Elaborar o documento de rich picture.

# Tarefas:
- [x] Aprimorar o rich picture baseado no esboço

# Critérios de aceitação:
- [x] documento de rich picture

**Comment by kayrocesar** [comment]
Rich Picture esboço:
![rich-esboço](https://user-images.githubusercontent.com/39713656/152462538-9b98a0e0-fe81-4440-883b-89761d256575.PNG)

Rich Picture Primeira versão aprimorada:
<img width="2255" alt="Rich picture (2)" src="https://user-images.githubusercontent.com/39713656/152462623-b6ef5114-2a7b-4a0e-a141-46250dce3ea6.png">

Rich Picture Segunda versão aprimorada:
<img width="2771" alt="Rich picture (5)" src="https://user-images.githubusercontent.com/39713656/152462685-50fd7fa6-c946-41b4-ad81-606d80d630bf.png">
