### ISSUE TITLE
Verificação - Especifiação Suplementar

### ISSUE THREAD

**Issue by klyssmannoliveira** [Requisitos-de-Software/2021.2-PontoFacil#42]
Verificação - Especifiação Suplementar

- [x] Elaborar documento de Verificação - Especifiação Suplementar

**Comment by klyssmannoliveira** [comment]
Aguardando a revisão do @kayrocesar

**Comment by kayrocesar** [comment]
> Aguardando a revisão do @kayrocesar

Revisado
