### ISSUE TITLE
Verificação - Instrospecção

### ISSUE THREAD

**Issue by joseluis-rt** [Requisitos-de-Software/2021.2-PontoFacil#47]
## Descrição da Issue

Elaborar documento de verificação da Instrospecção

## Tarefas:
- [x] Documento de verificação da Instrospecção

## Critérios de Aceitação:
- [x] Deve possuir checklist
- [x] Deve possuir gráfico de checklist

**Comment by joseluis-rt** [comment]
Aguardando a revisão do @kayrocesar .

**Comment by kayrocesar** [comment]
> Aguardando a revisão do @kayrocesar .

Revisado
