### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by klyssmannoliveira** [Requisitos-de-Software/2021.2-PontoFacil#7]
# Descrição:
Preparação dos slides da apresentação e gravação da apresentação.

# Tarefas:
- [x] Preparar slide
- [x] Gravação da apresentação 

# Critérios de aceitação:
- [x] slide da apresentação em pdf
- [x] vídeo de apresentação (link no youtube)

**Comment by eduardomr** [comment]
Issue concluida e documentada.
